# Generated by Django 2.1.3 on 2018-12-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181204_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
