# Generated by Django 2.1.3 on 2018-12-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilepage_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepage',
            old_name='picture',
            new_name='avatar',
        ),
    ]
